source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'fastandand'
gem 'slim'

gem 'pry-rails'

group :development, :test do
  gem 'rspec'
end

group :development do
  gem 'quiet_assets'
  gem 'pry-debundle'
  gem 'sequel'
  gem 'faker'
end

platforms :jruby do
  gem 'torquebox', '>= 4.0.0.beta3'

  gem 'activerecord-jdbc-adapter'
  gem 'jdbc-postgresql'
end

platforms :ruby do
  gem 'pg', '~> 0.15'
end
